version: "3"

tasks:
  docker-build:
    cmds:
      - docker build . --tag asia-northeast1-docker.pkg.dev/todo-app-407716/repo-0/img-0:latest --platform linux/amd64

  docker-push:
    cmds:
      - docker push asia-northeast1-docker.pkg.dev/todo-app-407716/repo-0/img-0:latest

  run-deploy:
    cmds:
      - gcloud run deploy server --image asia-northeast1-docker.pkg.dev/todo-app-407716/repo-0/img-0:latest --region asia-northeast1 --allow-unauthenticated

  artifacts-clean:
    cmds:
      - gcloud artifacts docker images delete asia-northeast1-docker.pkg.dev/todo-app-407716/repo-0/img-0 --quiet

  run:
    cmds:
      - RELEASE_STAGE=development go run ./main.go

  test:
    cmds:
      - RELEASE_STAGE=test go test

  dc-up:
    cmds:
      - docker compose -p todo-app up

  migrate-development:
    dotenv: [".env.development"]
    cmds:
      - migrate -database "$DATABASE_URL" -path ./migrations up
