version: "3"

tasks:
  # Development
  run:
    deps: [dc-up]
    cmds:
      - air
      - task: dc-stop

  dc-up:
    cmds:
      - docker compose -p todo-app up -d

  dc-stop:
    cmds:
      - docker compose -p todo-app stop

  migrate-development:
    dotenv: [".env.development"]
    cmds:
      - migrate -database "$DATABASE_URL" -path ./migrations up

  # Test
  test:
    cmds:
      - RELEASE_STAGE=test go test

  # Production
  deploy:
    cmds:
      - task: docker-build
      - task: docker-push
      - task: run-deploy

  docker-build:
    cmds:
      - docker build . --tag asia-northeast1-docker.pkg.dev/todo-app-407716/repo-0/img-0:latest --platform linux/amd64 --build-arg RELEASE_STAGE=production

  docker-push:
    cmds:
      - docker push asia-northeast1-docker.pkg.dev/todo-app-407716/repo-0/img-0:latest

  run-deploy:
    cmds:
      - gcloud run deploy server --image asia-northeast1-docker.pkg.dev/todo-app-407716/repo-0/img-0:latest --region asia-northeast1 --allow-unauthenticated

  artifacts-clean:
    cmds:
      - gcloud artifacts docker images delete asia-northeast1-docker.pkg.dev/todo-app-407716/repo-0/img-0 --quiet
